# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(10, 10, 415, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.result_label.setFont(font)
        self.result_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_label.setFrameShape(QtWidgets.QFrame.Box)
        self.result_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.result_label.setLineWidth(3)
        self.result_label.setMidLineWidth(0)
        self.result_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_label.setObjectName("result_label")
        #   %
        self.percent_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("%"))
        self.percent_button.setGeometry(QtCore.QRect(240, 410, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.percent_button.setFont(font)
        self.percent_button.setObjectName("percent_button")
        #   CE
        self.CE_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.remove())
        self.CE_button.setGeometry(QtCore.QRect(240, 80, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.CE_button.setFont(font)
        self.CE_button.setObjectName("CE_button")
        #  C
        self.c_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("C"))
        self.c_button.setGeometry(QtCore.QRect(345, 80, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.c_button.setFont(font)
        self.c_button.setObjectName("c_button")
        #   1/x
        self.reci_x_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.reci_x())
        self.reci_x_button.setGeometry(QtCore.QRect(20, 135, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reci_x_button.setFont(font)
        self.reci_x_button.setObjectName("reci_x_button")
        #    x^2
        self.x_square_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.square_x())
        self.x_square_button.setGeometry(QtCore.QRect(130, 135, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.x_square_button.setFont(font)
        self.x_square_button.setObjectName("x_square_button")
        #    x^1/2
        self.x_root_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.under_root())
        self.x_root_button.setGeometry(QtCore.QRect(240, 135, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.x_root_button.setFont(font)
        self.x_root_button.setObjectName("x_root_button")
        #   1/x^2        
        self.reci_x_square_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:self.reci_x_square())
        self.reci_x_square_button.setGeometry(QtCore.QRect(345, 135, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.reci_x_square_button.setFont(font)
        self.reci_x_square_button.setObjectName("reci_x_square_button")
        #  divide
        self.button_divide = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("/"))
        self.button_divide.setGeometry(QtCore.QRect(345, 190, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_divide.setFont(font)
        self.button_divide.setObjectName("button_divide")
        # 7
        self.button_7 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("7"))
        self.button_7.setGeometry(QtCore.QRect(20, 245, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        # 8
        self.button_8 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("8"))
        self.button_8.setGeometry(QtCore.QRect(130, 245, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        # 9
        self.button_9 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("9"))
        self.button_9.setGeometry(QtCore.QRect(240, 245, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        # mul
        self.button_mul = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("*"))
        self.button_mul.setGeometry(QtCore.QRect(345, 245, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_mul.setFont(font)
        self.button_mul.setObjectName("button_mul")
        # 4
        self.button_4 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("4"))
        self.button_4.setGeometry(QtCore.QRect(20, 300, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        # 5
        self.button_5 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("5"))
        self.button_5.setGeometry(QtCore.QRect(130, 300, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        # 6
        self.button_6 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("6"))
        self.button_6.setGeometry(QtCore.QRect(240, 300, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        # add
        self.button_add = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("+"))
        self.button_add.setGeometry(QtCore.QRect(345, 300, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_add.setFont(font)
        self.button_add.setObjectName("button_add")
        # 3
        self.button_3 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("3"))
        self.button_3.setGeometry(QtCore.QRect(20, 355, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        # 2
        self.button_2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("2"))
        self.button_2.setGeometry(QtCore.QRect(130, 355, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        # 1
        self.button_1 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("1"))
        self.button_1.setGeometry(QtCore.QRect(240, 355, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        # minus
        self.button_minus = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("-"))
        self.button_minus.setGeometry(QtCore.QRect(345, 355, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_minus.setFont(font)
        self.button_minus.setObjectName("button_minus")
        # 0
        self.button_0 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press("0"))
        self.button_0.setGeometry(QtCore.QRect(20, 410, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        # equals
        self.button_equal = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.equals())
        self.button_equal.setGeometry(QtCore.QRect(345, 410, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_equal.setFont(font)
        self.button_equal.setObjectName("button_equal")
        # dot
        self.dot_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.dot())
        self.dot_button.setGeometry(QtCore.QRect(130, 410, 85, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dot_button.setFont(font)
        self.dot_button.setObjectName("dot_button")
        # x^1/3
        self.cube_root_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.cube_root())
        self.cube_root_button.setGeometry(QtCore.QRect(130, 190, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cube_root_button.setFont(font)
        self.cube_root_button.setObjectName("cube_root_button")
        # 1/x^3
        self.reci_x_cube_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.reci_x_cube())
        self.reci_x_cube_button.setGeometry(QtCore.QRect(240, 190, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.reci_x_cube_button.setFont(font)
        self.reci_x_cube_button.setObjectName("reci_x_cube_button")
        # x^3
        self.x_cube_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.cube_x())
        self.x_cube_button.setGeometry(QtCore.QRect(20, 190, 85, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.x_cube_button.setFont(font)
        self.x_cube_button.setObjectName("x_cube_button")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)




    def square_x(self):
        labeltext = self.result_label.text()
        labeltext = labeltext+"**2"
        result = eval(labeltext)
        self.result_label.setText(str(result))



    def cube_x(self):
        labeltext = self.result_label.text()
        labeltext = labeltext+"**3"
        result = eval(labeltext)
        self.result_label.setText(str(result))



    def under_root(self):
        labeltext = self.result_label.text()
        try:
            labeltext = labeltext + "**(1/2)"
            result = eval(labeltext)
            self.result_label.setText(str(result))
        except:            
            self.result_label.setText("Error -1 in root")




    def cube_root(self):
        labeltext = self.result_label.text()
        try:
            labeltext = labeltext + "**(1/3)"
            result = eval(labeltext)
            self.result_label.setText(str(result))
        except:            
            self.result_label.setText("Error -1 in root")




    def reci_x_square(self):
        labeltext = self.result_label.text()
        try:
            labeltext = "1/(" +labeltext + "**2)"
            result = eval(labeltext)
            self.result_label.setText(str(result))
        except:            
            self.result_label.setText("Error 0 divisor")




        
    def reci_x_cube(self):
        labeltext = self.result_label.text()
        try:
            labeltext = "1/(" +labeltext + "**3)"
            result = eval(labeltext)
            self.result_label.setText(str(result))
        except:
            self.result_label.setText("Error 0 divisor")



    def reci_x(self):
        labeltext = self.result_label.text()
        try:
            labeltext = "1/"+labeltext
            result = eval(labeltext)
            self.result_label.setText(str(result))
        except:            
            self.result_label.setText("Error 0 divisor")






    def equals(self):
        labeltext = self.result_label.text()
        try:
            result = eval(labeltext)
            self.result_label.setText(str(result))
        except:
            self.result_label.setText("Error")





    def remove(self):
        labeltext = self.result_label.text()
        labeltext = labeltext[:-1]
        self.result_label.setText(labeltext)




    def dot(self):
        chars = ["+","-","*","/","%"]
        labeltext = self.result_label.text()
        if "." not in labeltext:
            self.result_label.setText(" {}.".format(labeltext))
        else:
            for i in chars:
                l1 = labeltext.split(i)
                if "." not in l1[-1]:
                    self.result_label.setText(" {}.".format(labeltext))





    def press(self,pressed):
        if pressed == "C":
            self.result_label.setText("0")
        else:
            if self.result_label.text() == "0":
                self.result_label.setText("")
            self.result_label.setText("{}{}".format(self.result_label.text(),pressed))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caculator"))
        self.result_label.setText(_translate("MainWindow", "0"))
        self.percent_button.setText(_translate("MainWindow", "%"))
        self.CE_button.setText(_translate("MainWindow", "CE"))
        self.c_button.setText(_translate("MainWindow", "C"))
        self.reci_x_button.setText(_translate("MainWindow", "1/x"))
        self.x_square_button.setText(_translate("MainWindow", "x^2"))
        self.x_root_button.setText(_translate("MainWindow", "(x)^1/2"))
        self.button_divide.setText(_translate("MainWindow", "/"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_mul.setText(_translate("MainWindow", "X"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_add.setText(_translate("MainWindow", "+"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.dot_button.setText(_translate("MainWindow", "."))
        self.cube_root_button.setText(_translate("MainWindow", "(x)^1/3"))
        self.reci_x_square_button.setText(_translate("MainWindow", "1/(x^2)"))
        self.reci_x_cube_button.setText(_translate("MainWindow", "1/(x^3)"))
        self.x_cube_button.setText(_translate("MainWindow", "x^3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
